package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 11 13:33:12 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void refreshPendingRentalView();
}

